### ISSUE TITLE
Add custom Flipper Name support

### ISSUE THREAD

**Issue by JMcrafter26** [TheSainEyereg/flipper-pc-monitor-backend#1]
Hi there,
I love the idea and how you have done this.

There is something I would like you to add: The ability to choose the flipper from a list of nearby devices, instead of having to rename the flipper.

This is all. 
Thank you for the app.

**Comment by TheSainEyereg** [comment]
Yeah, I was thinking about that. It's possible to implement Bluetooth device selection via inquire crate, but I just don't have time for that right now.

**Comment by detectingdragon77** [comment]
https://github.com/TheSainEyereg/flipper-pc-monitor-backend/blob/master/src/flipper_manager.rs I edited l
`name.contains("Flipper"))` to my flipper name in the source code.

> Hi there, I love the idea and how you have done this.
> 
> There is something I would like you to add: The ability to choose the flipper from a list of nearby devices, instead of having to rename the flipper.
> 
> This is all. Thank you for the app.

**Comment by ZekePolarisBSH** [comment]
I need the commands to start this so I can use Flipper on my PC

**Comment by AliHj98** [comment]
> I need the commands to start this so I can use Flipper on my PC

Check out https://github.com/jon4hz/fztea

**Comment by krzysiek123502** [comment]
But I have a problem because it is Linux Mint ,and my flipper name is Ufhooat what should I do?

**Comment by JMcrafter26** [comment]
> But I have a problem because it is Linux Mint ,and my flipper name is Ufhooat what should I do?

Just rename your flipper

**Comment by krzysiek123502** [comment]
But not to change the name of the flipper as much as possible.

**Comment by JMcrafter26** [comment]
> But not to change the name of the flipper as much as possible.

This would require changes in the pc backend. Either you change it and compile it yourself or you wait until the owner of this repo updates his code to allow custom flipper names (e.g. by choosing the flipper from a list of nearby Bluetooth devices)

**Comment by vollukas** [comment]
Hi I just modified the code so it asks you before scanning what string you want to scan for :) if you leave it blank then it tries all possible connections and actually finds my flipper (experimental). I will make pull request, but if you want it sooner (or if it gets declined) I can share the .exe file

**Comment by ZekePolarisBSH** [comment]
> > I need the commands to start this so I can use Flipper on my PC
> 
> Check out https://github.com/jon4hz/fztea

Why? I see nothing there that will help me. Basically spam dude.

**Comment by TheSainEyereg** [comment]
The app is now announcing itself as `PC Mon`, so there's now no need for custom names support
