### ISSUE TITLE
Connection problems

### ISSUE THREAD

**Issue by Linux0Hat** [TheSainEyereg/flipper-pc-monitor-backend#11]
Hello, I'm having trouble connecting.
I'm on linux and I have a custom fimware on my flipper zero (Xtrem). Could someone help me?
```
Found "hci0 (usb:v1D6Bp0246d0540)" adapter

- Scan will be searching for Flippers with a name that contains the string you enter here
- If you run official firmware you should be fine by entering 'Flipper' (case sensitive)
- Empty string will search for all possible Flippers (experimental)

Enter the name (for empty just press Enter): Rambzee

Scanning...
Connecting to Flipper hci0/dev_80_E1_26_6D_61_52
Failed to connect to Flipper hci0/dev_80_E1_26_6D_61_52
Connected to Flipper hci0/dev_80_E1_26_6D_61_52
Failed to find characteristic
Disconnected from Flipper hci0/dev_80_E1_26_6D_61_52
```

**Comment by itJunky** [comment]
Have same problem in linux and unleashed firmware:

$ RUST_BACKTRACE=full ./backend-linux-x86_64
Found "hci0 (usb:v1D6Bp0246d0540)" adapter
Scanning...
Connecting to Flipper hci0/dev_80_E1_26_F6_E6_BD
Failed to connect to Flipper hci0/dev_80_E1_26_F6_E6_BD
Connected to Flipper hci0/dev_80_E1_26_F6_E6_BD
Failed to find characteristic
Disconnected from Flipper hci0/dev_80_E1_26_F6_E6_BD


-----

80_E1_26_F6_E6_BD this is mac of my BT adapter on PC? Or it's hardcoded flipper mac? )

**Comment by Sanceilaks** [comment]
idk but it is can be bluetooth library issue
https://github.com/TheSainEyereg/flipper-pc-monitor-backend/blob/f1f02753d6fa0445f6a9f0bae17ca3a743aedabd/src/main.rs#L82

**Comment by Sanceilaks** [comment]
Software doesn`t work due to flipper update
