### ISSUE TITLE
Build for linux

### ISSUE THREAD

**Issue by itJunky** [TheSainEyereg/flipper-pc-monitor-backend#13]
Hello. Sources on the Rust? I'm not a rust programmer, but I want to recompile it from sources for me. Can you write simple instruction in readme how can I do this for flipper and my linux? May be just compile command with right parameters.

**Comment by Sanceilaks** [comment]
what is your gpu?

**Comment by Sanceilaks** [comment]
In any case, the application must be built under linux. for this you just need to build it without additional flags 
```bash cargo run``` or ```cargo build```
