### ISSUE TITLE
MALWARE

### ISSUE THREAD

**Issue by moymoussan** [TheSainEyereg/flipper-pc-monitor-backend#3]
Windows companion (exe) marked as malware:
[Virustotal](https://www.virustotal.com/gui/file/509b73ddf2ded95fcbc08864aadd7d5a0e557e1d6065e9f35815b9add90ecc67?nocache=1) 
[Hybrid Analysis](https://www.hybrid-analysis.com/sample/509b73ddf2ded95fcbc08864aadd7d5a0e557e1d6065e9f35815b9add90ecc67) 
![IMG_1537](https://github.com/TheSainEyereg/flipper-pc-monitor-backend/assets/66051741/08a24036-45c2-4e30-9089-36fcfc2ebaf1)

**Comment by Astrrra** [comment]
You know that this repo contains the source code for said companion, right? The whole thing's like 300 lines of code total, you can just look through it yourself and see that it doesn't do anything malicious.

Also, on your screenshot, the score is 2 out of 72, that's VERY low. The thing that triggered those two engines was probably the fact that this companion monitors the performance of the system, which is literally what it's made to do in the first place.
